use_frameworks!

platform :ios, '10.0'

target 'WPAPI_Example' do
  pod 'WPAPI', :path => '../'

  target 'WPAPI_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  end
end
